/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as FilmRouteImport } from './routes/film'
import { Route as ChIdRouteImport } from './routes/ch.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmRoute = FilmRouteImport.update({
  id: '/film',
  path: '/film',
  getParentRoute: () => rootRouteImport,
} as any)
const ChIdRoute = ChIdRouteImport.update({
  id: '/ch/$id',
  path: '/ch/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audio': typeof AudioRoute
  '/film': typeof FilmRoute
  '/ch/$id': typeof ChIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audio': typeof AudioRoute
  '/film': typeof FilmRoute
  '/ch/$id': typeof ChIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audio': typeof AudioRoute
  '/film': typeof FilmRoute
  '/ch/$id': typeof ChIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/audio' | '/film' | '/ch/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/audio' | '/film' | '/ch/$id'
  id: '__root__' | '/' | '/about' | '/audio' | '/film' | '/ch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AudioRoute: typeof AudioRoute
  FilmRoute: typeof FilmRoute
  ChIdRoute: typeof ChIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film': {
      id: '/film'
      path: '/film'
      fullPath: '/film'
      preLoaderRoute: typeof FilmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ch/$id': {
      id: '/ch/$id'
      path: '/ch/$id'
      fullPath: '/ch/$id'
      preLoaderRoute: typeof ChIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AudioRoute: AudioRoute,
  FilmRoute: FilmRoute,
  ChIdRoute: ChIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
